spring: # 可选
  redis:
    host: localhost
    port: 6379
    client-type: jedis  # 客户端技术选型 lettuce、jedis
    lettuce:
      pool:
        max-active: 16
    jedis:  # 直连模式，存在线程安全，需要保证访问量接口
      pool:
        max-active: 16


